In [1]:
import numpy as np

In [17]:
l = list(range(0,100))

# numpy arrays

In [18]:
l
a = np.array(l)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
a[(a > 20) & (a<80)]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79])

In [20]:
b = np.random.randint(0,100,100)

In [21]:
b

array([96,  7, 61,  9, 57, 98, 33, 93, 78, 80, 42, 86, 76, 83, 48,  4, 14,
       82, 76, 88,  0, 34, 10, 93, 91, 18,  9, 74, 36,  0,  8, 82, 92, 64,
       27, 66, 53, 79, 53, 69, 35, 14, 36, 12, 71, 12, 95,  0, 47, 16, 19,
       54, 14, 65, 46, 13, 53, 64,  8, 16, 25, 29, 69, 22, 36, 68,  4, 10,
       57, 64, 60, 61, 11, 36, 91, 20,  8, 93, 58, 43, 86, 67, 27, 24, 35,
       82, 59, 28, 63, 40, 39, 17,  1, 50, 98, 59, 22, 44, 23, 32])

In [22]:
b[(a > 20) & (a<80)]

array([34, 10, 93, 91, 18,  9, 74, 36,  0,  8, 82, 92, 64, 27, 66, 53, 79,
       53, 69, 35, 14, 36, 12, 71, 12, 95,  0, 47, 16, 19, 54, 14, 65, 46,
       13, 53, 64,  8, 16, 25, 29, 69, 22, 36, 68,  4, 10, 57, 64, 60, 61,
       11, 36, 91, 20,  8, 93, 58, 43])

In [23]:
(a > 20) & (a<80)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

# Lists

In [31]:
l2 = list(b)

cut = [j for (i,j) in zip(l,l2) if i>20 and i<80 ]
print(cut)

[34, 10, 93, 91, 18, 9, 74, 36, 0, 8, 82, 92, 64, 27, 66, 53, 79, 53, 69, 35, 14, 36, 12, 71, 12, 95, 0, 47, 16, 19, 54, 14, 65, 46, 13, 53, 64, 8, 16, 25, 29, 69, 22, 36, 68, 4, 10, 57, 64, 60, 61, 11, 36, 91, 20, 8, 93, 58, 43]


what is it doing?

In [ ]:
zip 